config/routes.rb
MixBox::Application.routes.draw do

  root :to => "index#index"

  match '/test_vim'=>'index#test_vim'

  devise_for :users, :path => "account", :controllers => {
      :registrations => :account,
      #:sessions => :sessions,
  }

  #用户空间
  resources :users, :path => "" do

  end

  resources :stories, :path => "/:login_name/" do

  end

end

app/models/story.rb
class Story
  include Mongoid::Document

  field :title, :type => String

  belongs_to :user

end

app/models/user.rb
#encoding=utf-8
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email, :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token, :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count, :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at, :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable
  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  #自定义字段
  field :login_name, :type => String #用户登录名字

  validates :login_name,
            :format => {:with => /\A\w+\z/, :message => '只允许数字、大小写字母和下划线'},
            :length => {:in => 3..20}, :presence => true,
            :uniqueness => {:case_sensitive => false}

  #使用login_name和email都可以登录
  def self.find_for_database_authentication(conditions)
    login = conditions.delete(:login_name)
    self.where(:login_name => /^#{login}$/i).first || self.where(:email => /^#{login}$/i).first
  end

  #显示名字
  field :nick_name, :type => String
  #拥有故事
  has_many :stories
end

app/controllers/account_controller.rb
class AccountController < Devise::RegistrationsController

  def create
    build_resource
    #自定义字段赋值 begin
    resource.login_name=params[resource_name][:login_name]
    resource.nick_name=params[resource_name][:nick_name]
    #end
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def edit
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render_404
      redirect_to :status=>404
  end

end

app/controllers/index_controller.rb
#encoding=utf-8
class IndexController < ApplicationController
  def index
    if user_signed_in?
      #如果用户登录,直接跳转到用户空间页面
      redirect_to user_path(current_user.login_name)
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def show
    @user = User.where(:login_name=> params[:login_name]).first;
    @story = @user.stories.where(:title=>params[:id]);
    #@story = Story.where(:title=>params[:id],:user=>@user).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def show
    if params[:id] != params[:id].downcase
       redirect_to request.path.downcase, :status=>301
       return
    end

    @user = User.where(:login_name=>params[:id]).first

    #For Test get Story Date
    @story = Story.all[0];

    render_404 if @user.nil?
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_error_messages.html.haml
- if target.errors.any?
  .alert.alert-block.alert-error
    %a.close{:href => "#"} ×
    %p
      %strong
        有 #{target.errors.count} 处问题导至无法提交:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/index/index.html.haml
.row
  .alert{:style=>'text-align:center'}
    %h2 2,052,073 people hosting over 3,588,161 repositories

.row
  .alert{:style=>'text-align:center'}
    %h2 Stories list

.row
  .alert{:style=>'text-align:center'}
    %h2 teams list

.row
  %ul.nav.nav-tabs#index-tabs
    %li.active
      %a{:href => "#star-stores"} Star Stores
    %li
      %a{:href => "#hot-stories"} Hot Stories
    %li
      %a{:href => "#hot-teams"} Hot Teams
    %li
      %a{:href => "#hot-users"} Hot Users
  .tab-content
    .tab-pane.active#star-stores
      .span4
        %table.table.table-striped
          %tr
            %td Story_1
          %tr
            %td Story_2
          %tr
            %td Story_3
          %tr
            %td Story_1
          %tr
            %td Story_2
          %tr
            %td Story_3
      .span6
        .story-introduction
          Story Introduction..............................
      .span2
        .story-image
          XXXXXXXXXXXXXXXXX
    .tab-pane#hot-stories
      .span4
        %table.table.table-striped
          %tr
            %td hot-story_1
          %tr
            %td hot-story_2
          %tr
            %td hot-story_3
      .span6
        .story-introduction
          Story Introduction..............................
      .span2
        .story-image
          XXXXXXXXXXXXXXXXX
    .tab-pane#hot-teams
      3
    .tab-pane#hot-users
      4

app/views/layouts/application.html.haml
!!!


%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "MixBox"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => root_path} MixBox
          .container.nav-collapse
            %ul.nav
              -if user_signed_in?
                %li= link_to '退出', destroy_user_session_path, :method => :delete
                %li= link_to '我的帐号', edit_user_registration_path
              -else
                %li= link_to '登录', new_user_session_path
                %li= link_to '注册', new_user_registration_path
    .container
      .content
        .row
          .span12
            = notice_message
        = yield
      %footer
        %p © Company 2012
    = javascript_include_tag "application"

app/views/stories/show.html.haml
.row
  .span12
    .navbar.navbar-inverse
      .navbar-inner
        %ul.nav
          %li
            %a{:href => "#"} Story
          %li
            %a{:href => "#"} Pull Requests
          %li
            %a{:href => "#"} Wiki
          %li
            %a{:href => "#"} Discuss
          %li
            %a{:href => "#"} Fork Graphs
          %li
            %a{:href => "#"} Admin

.row
  .span2
    Story Image
  .span3
    .row
      .span3
        Star *****
    .row
      .span3
        UserName/Story
  .span6.offset1
    %button Watch
    %button Fork(Count)
    %button Push(Count)

.row
  .span12.story-introduction
    %h3 Story Introduction
    .story-introduction-content
      =".................................................."

.row
  .span12.last-commit
    %h3 last-commit
    .last-commit-content
      ="..................................................."

.row
  .span12
    %form.form-search
      %input.input-Large.search-query
      %button.btn(type='submit') Search

.row
  .span12
    Story-Box

app/views/users/show.html.haml
.row
  .span2
    User Image
  .span3
    UserName(NickName)
  .span4.offset3
    %button Follow
    %button Message
    %button Other

.row
  .span6
    %ul
      %li
        E-mail:xxxxxxxxx@gmail.com
      %li
        Member Since:Jun 26,2008
      %li
        Last Visited:Jun 26,2008
      %li
        Blog:xxxxxx.xxxxx.com
      %li
        Location: Beijing

  .span2
    Followers:
    %strong 200
  .span2
    Stories:
    %strong 200
  .span2
    followed:
    %strong 200

.row
  .span6
    .row
      .span6
        %h3 Stories List
    .row
      .span6
        %form.form-search
          %input.input-Large.search-query
          %button.btn(type='submit') Search
    .row
      .span6.stories-list
        -20.times do
          .story
            .row
              .span2
                =link_to "Story-Name",story_path(@user.login_name,@story.title);
              .span1.offset1
                Type
              .span1
                Watchers
              .span1
                Forks
            .row
              .span6
                Story Introduction..............................................

  .span6
    .row
      .span6
        %h3 Public Activity List
    .row
      .span6
        %form.form-search
          %input.input-Large.search-query
          %button.btn(type='submit') Search
      .span6.activities-list
        -20.times do
          .activity
            .row
              .span1
                Icon
              .span5
                daigong starred saberma/shopqi 8 days ago
            .row
              .span5.offset1
                Flexible authentication solution for Rails with Warden.